language: python
cache: pip

python: 2.7

before_install:
  - export GALAXY_RELEASE=release_19.05

install:
  - pip install flake8 flake8-import-order planemo
  - planemo --version
  - git diff --quiet "$TRAVIS_COMMIT_RANGE" -- ; GIT_DIFF_EXIT_CODE=$?
  - |
    if [ "$GIT_DIFF_EXIT_CODE" -gt 1 ] ; then
        git remote set-branches --add origin master
        git fetch
        TRAVIS_COMMIT_RANGE=origin/master...
    fi
  - echo $TRAVIS_COMMIT_RANGE
  - |
    planemo ci_find_repos --exclude_from .tt_skip \
                          --changed_in_commit_range "$TRAVIS_COMMIT_RANGE" \
                          --output changed_repositories.list
  - cat changed_repositories.list

script:
  - set -e
  - cd "$TRAVIS_BUILD_DIR" && flake8 --exclude=.git .
  - |
    while read -r DIR; do
        planemo shed_lint --tools --ensure_metadata --report_level warn --fail_level error --recursive "$DIR"
    done < changed_repositories.list
  - |
    while read -r DIR; do
        planemo test --galaxy_branch "$GALAXY_RELEASE" "$DIR"
    done < changed_repositories.list
