language: python

before_install:
 - export GALAXY_REPO=${TRAVIS_BUILD_DIR}/galaxy
 - export PLANEMO_RELEASE=0.54.0

install:
 - sudo apt-get install -y python-virtualenv
 - virtualenv planemo-venv
 - . planemo-venv/bin/activate
 - pip install --upgrade pip setuptools
 - pip install planemo==$PLANEMO_RELEASE
 - git clone -b feature/isa_data_type_plus_enhancements https://github.com/phnmnl/galaxy ${GALAXY_REPO}
 - cp ${TRAVIS_BUILD_DIR}/tool-data/isa_cvterms.loc ${GALAXY_REPO}/tool-data/

script:
 - planemo lint ${TRAVIS_BUILD_DIR}/tools/converters/
 - planemo lint ${TRAVIS_BUILD_DIR}/tools/isacreate/isacreate_metabo.xml
 - planemo lint ${TRAVIS_BUILD_DIR}/tools/isaslicer/
 - planemo lint ${TRAVIS_BUILD_DIR}/tools/validators/
 - planemo test --galaxy_root=${GALAXY_REPO} --tool_data_table=${TRAVIS_BUILD_DIR}/config/tool_data_table_conf.xml ${TRAVIS_BUILD_DIR}/tools/converters/
 - planemo test --galaxy_root=${GALAXY_REPO} --tool_data_table=${TRAVIS_BUILD_DIR}/config/tool_data_table_conf.xml ${TRAVIS_BUILD_DIR}/tools/isacreate/isacreate_metabo.xml
 - planemo test --galaxy_root=${GALAXY_REPO} --tool_data_table=${TRAVIS_BUILD_DIR}/config/tool_data_table_conf.xml ${TRAVIS_BUILD_DIR}/tools/isaslicer/
 - planemo test --galaxy_root=${GALAXY_REPO} --tool_data_table=${TRAVIS_BUILD_DIR}/config/tool_data_table_conf.xml ${TRAVIS_BUILD_DIR}/tools/validators/


branches:
  only:
  - master
  - develop
