#!/bin/bash
# vi: fdm=marker

# Constants {{{1
################################################################

PROG_NAME=$(basename $0)
PROG_PATH=$(dirname $0)
VENV=$PROG_PATH/isavenv

# Main {{{1
################################################################

virtualenv -q -p python3 $VENV
source $VENV/bin/activate
pip install isatools==0.9.5 click==6.7
make test
deactivate
rm -rf $venv
