#!/bin/bash
# vi: fdm=marker

# Constants {{{1
################################################################

PROG_NAME=$(basename $0)
PROG_PATH=$(dirname $0)
VENV=$PROG_PATH/isavenv

# Main {{{1
################################################################

virtualenv -q -p python3.6 $VENV
source $VENV/bin/activate
pip3 install click==6.7
git clone -b isa_hackathon git://github.com/ISA-tools/isa-api.git $VENV/isapi
pip3 install -e $VENV/isapi
make test
deactivate
rm -rf $venv
