auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }}"
categories:
- Convert Formats
- Metabolomics
- Transcriptomics
homepage_url: https://isa-tools.org/
long_description: |
  ISA tools help to manage a diverse set of life science, environmental and
  biomedical experiments employing a combination of technologies.

  Built around the 'Investigation', 'Study' and 'Assay' data model and
  serializations (tabular, JSON and RDF), the ISA framework helps you to provide
  rich description of the experimental metadata.
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/isatools
suite:
  name: "suite_isatools"
  description: "ISA tools suite"
type: unrestricted
